### ISSUE TITLE
Invalid output: "Publishing 'None' branch" on release publish.

### ISSUE THREAD

**Issue by realyze** [htgoebel/gitflow#6]
Steps to reproduce:
1) git flow release start 1.0.1
2) git flow release publish

Result:
$> git flow release publish
publishing release branch 1.0.1
Username for 'https://github.com': realyze
Password for 'https://realyze@github.com': 

Summary of actions:
- A new remote branch 'None' was created
- The local branch 'None' was configured to track the remote branch
- You are now on branch 'None'

Expected result:
Branch name is not 'None'.

That looks like a pretty minor bug and probably very easy to fix, but I don't have time to dig in the the code now and send a pull request, so I'm just filing a bug.

**Comment by htgoebel** [comment]
fixed in cc646ba.
