### ISSUE TITLE
typo in merge exception handling

### ISSUE THREAD

**Issue by ebridges** [htgoebel/gitflow#8]
Thanks for a really useful product!

A script in which I'm using gitflow caused this error:

```
  File "/Users/ebridges/.virtualenvs/irs/lib/python2.7/site-packages/gitflow-0.5.1-py2.7.egg/gitflow/branches.py", line 269, in merge
    text = text + '\n' + e.stderr
UnboundLocalError: local variable 'text' referenced before assignment
```

This is due to two small spelling typos in [`branches.py`](https://github.com/htgoebel/gitflow/blob/develop/gitflow/branches.py#L269)

``` python
        except GitCommandError, e:
            txt = stdout.getvalue().rstrip()
            if e.stderr:
                text = text + '\n' + e.stderr
            raise MergeError(txt)
```

That line should be: `txt = txt + '\n' + e.stderr`.

**Comment by htgoebel** [comment]
Fixed in e41537552b. Thanks for reporting.
